apiVersion: v1
kind: Namespace
metadata:
  name: fio-tools
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fio-tools
  namespace: fio-tools
data:
  # Directory to save the output data (It's not a fio parameter).
  gen-data.output-dir: '/app/benchmarks'
  # Prefix filename with this directory (see FILENAME).
  gen-data.directory: '/app/data'
  # The block size in bytes used for I/O units. Default: 4096.
  gen-data.block-size: '4096'
  # If value is true, use non-buffered I/O. Default: false.
  gen-data.direct: '1'
  # Fio normally makes up a filename based on the job name.
  gen-data.filename: 'fio-test.bin'
  # Defines how the job issues I/O to the file.
  # libaio Linux native asynchronous I/O.
  gen-data.io-engine: 'libaio'
  # By default, fio will log an entry in the iops, latency, or bw log
  # for every I/O that completes. When writing to the disk log, that
  # can quickly grow to a very large size. Setting this option makes
  # fio average the each log entry over the specified period of time,
  # reducing the resolution of the log.
  gen-data.log-avg-msec: '1000'
  # Seed the random number generator used for random I/O patterns in a
  # predictable way so the pattern is repeatable across runs.
  # Default: true.
  gen-data.rand-repeat: '1'
  # Tell fio to terminate processing after the specified period of time.
  gen-data.runtime: '30'
  # How much data are we going to be reading/writing.
  gen-data.size: '50Mi'
  # If set, fio will run for the duration of the runtime specified
  # even if the file(s) are completely read or written
  gen-data.time-based: '0'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-tools
  namespace: fio-tools
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fio-tools
  namespace: fio-tools
spec:
  selector:
    matchLabels:
      app: fio-tools
  template:
    metadata:
      labels:
        app: fio-tools
    spec:
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: fio-tools
        - name: benchmarks
          emptyDir: {}
        - name: plots
          emptyDir: {}
        containers:
        - name: fio-frontend
          imagePullPolicy: Always
          image: artmr/fio-http-server:0.1
          volumeMounts:
          - name: benchmarks
            mountPath: /server/benchmarks
          - name: plots
            mountPath: /server/plots
          ports:
          - containerPort: 8000
        initContainers:
        - name: fio-gen-data
          imagePullPolicy: Always
          image: artmr/fio-gen-data:0.1
          args: ["/app/job-templates/random-template.fio"]
          volumeMounts:
          - name: data 
            mountPath: /app/data
          - name: benchmarks
            mountPath: /app/benchmarks
          env:
            - name: OUTPUT_DIR
              valueFrom:
                configMapKeyRef:
                  name: fio-tools
                  key: gen-data.output-dir
            - name: BLOCK_SIZE
              valueFrom:
                configMapKeyRef:
                  name: fio-tools
                  key: gen-data.block-size
            - name: DIRECT
              valueFrom:
                configMapKeyRef:
                  name: fio-tools
                  key: gen-data.direct
            - name: DIRECTORY
              valueFrom:
                configMapKeyRef:
                  name: fio-tools
                  key: gen-data.directory
            - name: FILENAME
              valueFrom:
                configMapKeyRef:
                  name: fio-tools
                  key: gen-data.filename
            - name: IO_ENGINE
              valueFrom:
                configMapKeyRef:
                  name: fio-tools
                  key: gen-data.io-engine
            - name: LOG_AVG_MSEC
              valueFrom:
                configMapKeyRef:
                  name: fio-tools
                  key: gen-data.log-avg-msec
            - name: RAND_REPEAT
              valueFrom:
                configMapKeyRef:
                  name: fio-tools
                  key: gen-data.rand-repeat
            - name: RUNTIME
              valueFrom:
                configMapKeyRef:
                  name: fio-tools
                  key: gen-data.runtime
            - name: SIZE
              valueFrom:
                configMapKeyRef:
                  name: fio-tools
                  key: gen-data.size
            - name: TIME_BASED
              valueFrom:
                configMapKeyRef:
                  name: fio-tools
                  key: gen-data.time-based
        - name: fio-gen-plots
          imagePullPolicy: Always
          image: artmr/fio-gen-plots:0.1
          args: ["-L", "-i", "/benchmarks"]
          volumeMounts:
          - name: benchmarks
            mountPath: /benchmarks
          - name: plots
            mountPath: /plots
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fio-tools
  name: fio-tools
  namespace: fio-tools
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31367
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: fio-tools
  type: NodePort
